### ISSUE TITLE
Bug in BBC Micro source for Dungeon Of Doom

### ISSUE THREAD

**Issue by ahope1** [jggames/trs80mc10#3]
Hi, Jim. Just letting you know that Brian and I have been discussing [your excellent analysis](http://jimgerrie.blogspot.com/2022/12/usborne-books-dungeon-of-doom-1984.html) of the BBC Micro source for Dungeon Of Doom in Brian’s GitHub repo:

https://github.com/bchiha/dungeon-of-doom/issues/2

**Comment by jggames** [comment]
Glad to hear.  Not sure if all my bugs reports are completely legit.  Some might emerge from the porting process.  But maybe some are useful to know about for the Beep version.

Jim

Sent from Mail for Windows

From: Ant
Sent: Monday, December 12, 2022 5:27 AM
To: jggames/trs80mc10
Cc: Subscribed
Subject: [jggames/trs80mc10] Bug in BBC Micro source for Dungeon Of Doom (Issue #3)

Hi, Jim. Just letting you know that Brian have I have been discussing your excellent analysis of the BBC Micro source for Dungeon Of Doom in Brian’s GitHub repo:
bchiha/dungeon-of-doom#2
